services:
  - type: web
    name: csv-cleaner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYENV_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
